### ISSUE TITLE
Error loading plugin, node_modules/homebridge-envisalink-ademco does not contain the 'homebridge' package in 'engines'

### ISSUE THREAD

**Issue by sjsli** [haywirecoder/homebridge-envisalink-ademco#1]
First and foremost thank you for porting the DSC code to support Ademco panels!  I've had an envisalink (version 3) with an Ademco vista 20p panel for sometime now but of course couldn't integrate it with Homebridge due to the lack of support.  I'm running into an error when starting Homebridge and I'm hopeful you can provide some guidance.  Thank you!

[5/31/2020, 15:06:16] ====================
[5/31/2020, 15:06:16] ERROR LOADING PLUGIN homebridge-envisalink-ademco:
[5/31/2020, 15:06:16] Error: Plugin /usr/lib/node_modules/homebridge-envisalink-ademco does not contain the 'homebridge' package in 'engines'.
    at Plugin.load (/usr/lib/node_modules/homebridge/src/plugin.ts:150:13)
    at /usr/lib/node_modules/homebridge/src/pluginManager.ts:120:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/usr/lib/node_modules/homebridge/src/pluginManager.ts:118:18)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:149:24)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
[5/31/2020, 15:06:16] ====================

**Comment by haywirecoder** [comment]
Just enter the world of homebridge/Hoobs, so this is my first attempt to write a homebridge plug-in. Base on few other posting with similar issues, it seem it is related to the engine declaration. I have place 
"engines": {
    "homebridge": ">=0.2.0",
    "node": ">=0.12.0"
  },
within the package.json in hopes it corrects the issue for you.

**Comment by sjsli** [comment]
That resolved it.  Thank you!
