### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by sjsli** [haywirecoder/homebridge-envisalink-ademco#2]
Thanks for your work on this plugin, it's really starting to come along!  After upgrading to 1.0.11 I'm running into a new issue:

[6/6/2020, 14:19:22] TypeError: Cannot read property 'length' of undefined
    at new EnvisalinkPlatform (/usr/lib/node_modules/homebridge-envisalink-ademco/index.js:34:41)
    at /usr/lib/node_modules/homebridge/src/server.ts:396:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

I'm running Homebridge 1.1.0

Thanks!

**Comment by haywirecoder** [comment]
This error would indicate that you have no partitions defined. The following entries should appear in configuration file. 
"partitions": [
                {
                    "name": "House Alarm"
                }
           ],
I will set some defaults and update the read in the next versions to suppress this type of fault.

**Comment by sjsli** [comment]
Perfect, defining the partition resolved it.  Thank you again!
