### ISSUE TITLE
2.0.3 - Ignoring bypass request

### ISSUE THREAD

**Issue by HerbM3** [haywirecoder/homebridge-envisalink-ademco#32]
My bypass seems to have stopped working recently. I believe it might have happened after I updated to 2.0.3

 [11/22/2022, 4:32:16 PM] [Envisalink-Ademco] setByPass:  Bypass set -  true
[11/22/2022, 4:32:16 PM] [Envisalink-Ademco] Alarm is READY no action required. Ignoring bypass request.
[11/22/2022, 4:32:16 PM] [homebridge-envisalink-ademco] Characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.
[11/22/2022, 4:32:16 PM] [homebridge-envisalink-ademco] Error: 
    at On.Characteristic.characteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2138:105)
    at /homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1756:22
    at /homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at EnvisalinkCustomAccessory.setByPass (/homebridge/node_modules/homebridge-envisalink-ademco/accessories/customAccessory.js:211:17)
    at On.<anonymous> (/homebridge/node_modules/homebridge-envisalink-ademco/accessories/customAccessory.js:60:62)
    at On.emit (node:events:513:28)
    at /homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1725:16
    at new Promise (<anonymous>)
    at On.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1723:14)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
[11/22/2022, 4:32:17 PM] [Envisalink-Ademco] Command | %00,01,1C28,08,00,PRIME SLIDER    CHIME,Rdy to Arm$,00,01,1C28,08,00,PRIME SLIDER    CHIME,Rdy to Arm | Acknowledged
[11/22/2022, 4:32:17 PM] [Envisalink-Ademco] Envisakit Operation: updatekeypad
[11/22/2022, 4:32:17 PM] [Envisalink-Ademco] systemUpdate: Status changed -  {
  partition: '01',
  code: {
    icon: [ 3, 5, 10, 11, 12 ],
    zone: '08',
    beep: 'off',
    txt: 'PRIME SLIDER    CHIME'
  },
  status: 'Virtual Keypad Update',
  keypadledstatus: {
    alarm: false,
    alarm_in_memory: false,
    armed_away: false,
    ac_present: true,
    bypass: false,
    chime: true,
    not_used1: false,
    armed_zero_entry_delay: false,
    alarm_fire_zone: false,
    system_trouble: false,
    not_used2: true,
    not_used3: true,
    ready: true,
    fire: false,
    low_battery: false,
    armed_stay: false
  },
  mode: 'READY'
}

**Comment by haywirecoder** [comment]
Hi,

Nothing changed from previous version (e.g. 2.0.1) in regards to the alarm bypass code and I have been personally using it without issue. However, I did notice a best coding practice that I wasn't following from (https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings). I have updated /homebridge/node_modules/homebridge-envisalink-ademco/accessories/customAccessory.js and upload it to the code repo. Please replace your current customAccessory.js with the repo version and let me know if the error disappears.

In addition please make sure your running the lastest homebridge v1.5.1
