### ISSUE TITLE
[Envisalink-Ademco] Command not successful. No TPI session establish.

### ISSUE THREAD

**Issue by allenlbrown** [haywirecoder/homebridge-envisalink-ademco#35]
New to HomeBridge! Connected to HomeKit and installed plugin successfully but can't seem to connect to Envisalink 4. Panel works fine with Eyezon iPhone and web app..

[1/16/2023, 11:57:12 AM] [Envisalink-Ademco] Starting connection to envisalink module at: 192.168.1.176, port: 4025
[1/16/2023, 11:58:12 AM] [Envisalink-Ademco] Arming alarm to Stay (Home). [Partition 1]
**[1/16/2023, 11:58:12 AM] [Envisalink-Ademco] Command not successful. No TPI session establish.**
[1/16/2023, 11:58:22 AM] [Envisalink-Ademco] Alarm is READY no action required. Ignoring bypass request.
[1/16/2023, 11:59:22 AM] [Envisalink-Ademco] EnvisaLink Network Error:  Error: connect ETIMEDOUT 192.168.1.176:4025
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.176',
  port: 4025
}
[1/16/2023, 11:59:27 AM] [Envisalink-Ademco] Session closed unexpectedly. Re-establishing Session...
[1/16/2023, 11:59:27 AM] [Envisalink-Ademco] Starting connection to envisalink module at: 192.168.1.176, port: 4025

**Comment by haywirecoder** [comment]
Hi,

The iPhone and web app are not using the Envisakit TPI local connection, so it's not a good test. The error is indicating you're having TCP/IP connection issues to the module. This is low level connection error so either your TCP/IP connection is not stable on Homebridge server or on Envisakit module. 
In addition
1. Asure nothing else is locally connecting to module as indicated in the readme this can have unexpected results.
2. Enabled TPI interface in module.

**Comment by allenlbrown** [comment]
I responded to your other reply with the log. I read the connection warning in the readme but don’t have anything else connected to envisalink, just the network and panel. That said, I know just enough about this to be dangerous so let me know what to check. Thanks again!

**Comment by allenlbrown** [comment]
Other email didn't post so I copied here:

Thanks for the reply! FYI I’m running Homebridge on a QNAP NAS..

1. v2.0.3
2. Panel is always “ready”, module doesn’t connect
3. Here’s the log; I restarted Homebridge and attempted to arm the panel:

[1/18/2023, 8:15:35 AM] [Homebridge UI] Homebridge restart request received
[1/18/2023, 8:15:35 AM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[1/18/2023, 8:15:35 AM] [Homebridge UI] Sending SIGTERM to Homebridge
[1/18/2023, 8:15:35 AM] Got SIGTERM, shutting down Homebridge...
[1/18/2023, 8:15:40 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/18/2023, 8:15:45 AM] [HB Supervisor] Restarting Homebridge...
[1/18/2023, 8:15:45 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules -D --strict-plugin-resolution
[1/18/2023, 8:15:45 AM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 9369
[1/18/2023, 8:15:46 AM] Loaded config.json with 0 accessories and 4 platforms.
[1/18/2023, 8:15:47 AM] Loaded 11 cached accessories from cachedAccessories.
[1/18/2023, 8:15:47 AM] ---
[1/18/2023, 8:15:47 AM] Disabled plugin: homebridge-envisalink@1.2.9
[1/18/2023, 8:15:47 AM] ---
[1/18/2023, 8:15:47 AM] Loaded plugin: homebridge-envisalink-ademco@2.0.3
[1/18/2023, 8:15:47 AM] Registering platform 'homebridge-envisalink-ademco.Envisalink-Ademco'
[1/18/2023, 8:15:47 AM] ---
[1/18/2023, 8:15:47 AM] Loaded plugin: homebridge-myq@2.9.0
[1/18/2023, 8:15:47 AM] Registering platform 'homebridge-myq.myQ'
[1/18/2023, 8:15:47 AM] ---
[1/18/2023, 8:15:47 AM] Loading 4 platforms...
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Initializing Envisalink-Ademco platform...
[1/18/2023, 8:15:47 AM] Ignoring config for the platform "Envisalink" in your config.json as the plugin "homebridge-envisalink" has been disabled.
[1/18/2023, 8:15:47 AM] [myQ] Initializing myQ platform...
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Loading accessory from cache: House
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Loading accessory from cache: Carbon Monoxide 
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Loading accessory from cache: Smoke Detector
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Loading accessory from cache: Entry / Exit
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Loading accessory from cache: Kitchen Windows
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Loading accessory from cache: Glass Break
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Loading accessory from cache: Balcony Doors
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Loading accessory from cache: Master Bedroom Windows
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Loading accessory from cache: Office Windows
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Loading accessory from cache: Chime
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Configuring Honeywell VISTA-20P for Homekit...
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] refreshAccessories: Partition number -  1  configured.
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] refreshAccessories: Zone number -  1  configured.
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] refreshAccessories: Zone number -  2  configured.
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] refreshAccessories: Zone number -  3  configured.
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] refreshAccessories: Zone number -  4  configured.
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] refreshAccessories: Zone number -  5  configured.
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] refreshAccessories: Zone number -  6  configured.
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] refreshAccessories: Zone number -  7  configured.
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] refreshAccessories: Zone number -  8  configured.
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Partition configured: 1
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Zone accessories configured: 8
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Chime toggle accessory configured.
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Starting connection to envisalink module at: 192.168.1.176, port: 4025
[1/18/2023, 8:15:47 AM] Publishing bridge accessory (name: Homebridge B3E4, publishInfo: {
  username: '0E:E0:8D:1D:B3:E4',
  port: 51982,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'bonjour-hap'
}).
Setup Payload:
x-hm://0024YDID8UHBP
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 897-63-900 │     
    └────────────┘     
                       
[1/18/2023, 8:15:47 AM] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge B3E4) is running on port 51982.
[1/18/2023, 8:15:48 AM] [Envisalink-Ademco] getPanelStatusLowBattery: Return Low Battery Status -  0
[1/18/2023, 8:15:49 AM] [myQ] myQ API: Successfully connected to the myQ API.
[1/18/2023, 8:15:50 AM] [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: CG086016802D, gateway: GW0F000C812B).
[1/18/2023, 8:15:50 AM] [myQ] myQ API: Discovered device family gateway: Hub [Liftmaster WiFi GDO AC 3/4 HP] (serial number: GW0F000C812B).
[1/18/2023, 8:16:19 AM] [Envisalink-Ademco] getPanelStatusLowBattery: Return Low Battery Status -  0
[1/18/2023, 8:16:20 AM] [Envisalink-Ademco] setTargetState: Homekit alarm requested set -  0
[1/18/2023, 8:16:20 AM] [Envisalink-Ademco] Arming alarm to Stay (Home). [Partition 1]
[1/18/2023, 8:16:20 AM] [Envisalink-Ademco] setAlarmState: Partition state command issued.
[1/18/2023, 8:16:20 AM] [Envisalink-Ademco] Command not successful. No TPI session establish.
[1/18/2023, 8:16:20 AM] [Envisalink-Ademco] setAlarmState: Command not sent returning home state  3
[1/18/2023, 8:16:20 AM] [homebridge-envisalink-ademco] Characteristic 'Security System Target State': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.
[1/18/2023, 8:16:20 AM] [homebridge-envisalink-ademco] Error: 
    at SecuritySystemTargetState.Characteristic.characteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at /homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2627:22
    at /homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:15:18
    at EnvisalinkPartitionAccessory.setTargetState (/homebridge/node_modules/homebridge-envisalink-ademco/accessories/partitionAccessory.js:204:10)
    at SecuritySystemTargetState.<anonymous> (/homebridge/node_modules/homebridge-envisalink-ademco/accessories/partitionAccessory.js:66:52)
    at SecuritySystemTargetState.emit (node:events:513:28)
    at /homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2596:16
    at new Promise (<anonymous>)
    at SecuritySystemTargetState.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2594:14)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
[1/18/2023, 8:16:21 AM] [Envisalink-Ademco] Setting Alarm state to READY

**Comment by haywirecoder** [comment]
Confused,

Did you open two issues? I am not clear about your problem since Characteristic error and TCP/IP connections error are very different things. The reason you getting a Characteristic error is you never got a successful connection. 
That said, it shouldn't give an error if the TPI session is not established about Characteristic which can be fixed, but that will NOT fix your IP issues.  Did you confirm that TPI is enabled?

**Comment by allenlbrown** [comment]
Same issue, just turned on the logging, restarted and copied everything afterward. Where would I check for TPI being enabled?

**Comment by haywirecoder** [comment]
Hi,

Actually different issue from issue #36, hence why I delete your post in that issue since it is very different. Since that one doesn't relate to connection failure to the Envisalink module.

To see if TPI is enabled go to the web interface and click on network. You should see if it is "online"  and the alert should be enabled... assuming it is like Envisakit ver 3.

**Comment by allenlbrown** [comment]
Seems to be online:

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/122745112/213279665-d993762d-63a9-43c9-86c7-3d1b5a03328f.png">

I changed to static after the issue was sent.

Sorry for any confusion, I know just enough to be dangerous..

**Comment by haywirecoder** [comment]
Hmm,
Two things: 
1. Your IP for the server is **192.168.0.176**, but the log is showing you're trying to connect to 
[1/18/2023, 8:15:47 AM] [Envisalink-Ademco] Starting connection to envisalink module at: **192.168.1.176,** port: 4025

You need to change your configuration to match the module IP address.

2. EnvisaLink TPI Status is not in your screenshot.  In Envislink 3 it is clearly marked after the EnvisaAlarm Status. I don't have Envisalink 4, it could be buried in another screen or enabled by default...etc. You would have to contact Envisalink for help or refer to your documentation.

**Comment by allenlbrown** [comment]
Argh! Can’t believe I typed the IP wrong! Seems to be working now. Thanks..

**Comment by haywirecoder** [comment]
Great...happy its working for you
